import type { Metadata } from "next";
import { Abril_Fatface, Source_Serif_4 } from 'next/font/google';
import "./globals.css";

const abrilFatface = Abril_Fatface({ subsets: ['latin'],  weight: ['400'], variable: '--font-abril', });
const sourceSerif4 = Source_Serif_4({ subsets: ['latin'], variable: '--font-source', });

export const metadata: Metadata = {
  title: "Barber's School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${abrilFatface.className} ${sourceSerif4.className}`}
      >
        {children}
      </body>
    </html>
  );
}
